/* ------------------------------------------------------------------
   Core domain types for LastMinute.ai
   ------------------------------------------------------------------ */

/** Difficulty level chosen by the student */
export type Difficulty = "easy" | "medium" | "hard";

/** A single concept extracted from uploaded materials */
export interface Concept {
  id: string;
  name: string;
  description: string;
  /** IDs of prerequisite concepts */
  dependencies: string[];
  /** Estimated importance for the exam (0–1) */
  weight: number;
}

/** Represents an uploaded study document */
export interface StudyDocument {
  id: string;
  filename: string;
  /** mime type, e.g. "application/pdf" */
  type: string;
  /** Raw extracted text */
  content: string;
  uploadedAt: Date;
}

/** A course/session the student creates */
export interface Course {
  id: string;
  name: string;
  difficulty: Difficulty;
  documents: StudyDocument[];
  concepts: Concept[];
  createdAt: Date;
}

/** A step inside a story scenario */
export interface ScenarioStep {
  id: string;
  narrative: string;
  /** Concept IDs this step covers */
  conceptIds: string[];
  /** Possible user choices (if interactive) */
  choices?: { label: string; isCorrect: boolean; feedback: string }[];
  /** Optional media attachment */
  media?: { type: "image" | "gif" | "diagram"; url: string; alt: string };
}

/** A full interactive scenario generated by the story engine */
export interface Scenario {
  id: string;
  courseId: string;
  title: string;
  steps: ScenarioStep[];
}

/** Result after a student completes a scenario or quiz */
export interface EvaluationResult {
  scenarioId: string;
  score: number;
  /** Per-concept mastery deltas */
  conceptScores: Record<string, number>;
  feedback: string;
  nextAction: "continue" | "review" | "advance";
}

/** Chat message between the user and the tutor */
export interface ChatMessage {
  role: "user" | "assistant";
  content: string;
  timestamp: Date;
}
